### ISSUE TITLE
Data Visualization Year to Year

### ISSUE THREAD

**Issue by courtlam** [codeforokc/okc-budget-data#7]
![screen shot 2016-02-22 at 7 12 51 pm](https://cloud.githubusercontent.com/assets/11417361/13238432/8689dc46-d998-11e5-98ac-d1c4716a8969.png)

http://www.visualcinnamon.com/2015/10/different-look-d3-radar-chart.html

**Comment by mascott** [comment]
Thanks!

Just so we remember later, we talked some about trying to group the categories into smaller related sets instead of trying fit all of the data into this graph.

**Comment by mkchandler** [comment]
This issue was moved to codeforokc/openbudgetokc#42
