### ISSUE TITLE
 Still a bit noisy?

### ISSUE THREAD

**Issue by bshambaugh** [codeforokc/okc-budget-data#9]
This is a great visualization that gives a broad overview of all of the things with city government. You cannot see it, but I loaded to my apache server at http://localhost/codeokctest/circles.html . :) I enjoy the adaptive zoom, that gives more detail as I narrow down on a particular circle. However, I get the impression that it is a bit noisy. Perhaps there is a way to display what I am seeing for a particular zoom, see facets for each bubble, or do some sort of keyword search over everything there?

**Comment by bshambaugh** [comment]
CSci 572 - Data Visualization Demo (Solr + D3) https://www.youtube.com/watch?v=r-K63Iie210

**Comment by mkchandler** [comment]
Thanks for the info @bshambaugh. Do you have a visual example of what you are talking about that way we could see (maybe screenshot or demo)?

**Comment by bshambaugh** [comment]
I like this one: https://www.youtube.com/watch?v=r-K63Iie210

-Brent Shambaugh

Website: bshambaugh.org

**Comment by bshambaugh** [comment]
I see banana in this screencast. Perhaps they are using this code?
https://github.com/lucidworks/banana I would need to try it out.

-Brent Shambaugh

Website: bshambaugh.org

**Comment by mkchandler** [comment]
This issue was moved to codeforokc/openbudgetokc#43
